services:
  web:
    build: ./website
    ports:
      - "8000:80"
      - "24678:24678"
    volumes:
      - "./website:/home/node/app"
    depends_on:
      - cms_api
  cms_frontend:
    build: ./cms_frontend
    ports:
      - "8800:8800"
      - "24679:24679"
    volumes:
      - "./cms_frontend:/home/node/app"
    depends_on:
      - cms_api
  cms_api:
    build: ./cms_api
    ports:
      - "9000:9000"
    depends_on:
      - cms_db
  cms_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
